### ISSUE TITLE
use-async-effect.ts test flakes

### ISSUE THREAD

**Issue by brandongregoryscott** [AndcultureCode/AndcultureCode.JavaScript.React#50]
During a recent merge & package preparation, I noticed this test failure. After a few re-runs, I noticed it on & off passing/failing. Investigate this implementation & corresponding test to ensure it is working as expected.

```
 FAIL  src/hooks/use-async-effect.test.tsx
  ● useAsyncEffect › isMounted equals false after cleanup

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      80 |         await cleanup();
      81 |         await waitFor(() => expect(mockedMethod).toBeCalledTimes(1));
    > 82 |         expect(actualIsMountedValue).toBe(expectedIsMountedValue);
         |                                      ^
      83 |     });
      84 | });
      85 | 

      at src/hooks/use-async-effect.test.tsx:82:38
      at step (src/hooks/use-async-effect.test.tsx:33:23)
      at Object.next (src/hooks/use-async-effect.test.tsx:14:53)
      at fulfilled (src/hooks/use-async-effect.test.tsx:5:58)
```

**Comment by brandongregoryscott** [comment]
Looks like this is happening for automated dependabot builds, too 😞 https://travis-ci.org/github/AndcultureCode/AndcultureCode.JavaScript.React/builds/747710872 from PR #51 

Going to try to dig into it this week so we aren't getting hung up by broken builds
